- hosts: localhost
  connection: local
  vars:
    ansible_python_interpreter: python
  tasks:

    - name: launch an instance
      os_server:
        name: "{{ host_name }}"
        state: present
        image: CentOS-7
        flavor_ram: 4096
        key_name: "{{ key_name }}"
        terminate_volume: yes
        volume_size: 20
        nics:
          - net-name: public
      register: example_server

    - name: get facts about the server (including its public v4 IP address)
      os_server_facts:
        server: "{{ host_name }}"
      until: example_server.server.public_v4 != ""
      retries: 5
      delay: 10

    - set_fact:
        public_v4: "{{ example_server.server.public_v4 }}"

    - name: add the server to our ansible inventory
      add_host: hostname={{ public_v4 }} groups=web ansible_ssh_user=dhc-user ansible_ssh_private_key_file={{ private_key }}

    - name: wait for ssh to be available
      wait_for: host={{ public_v4 }} port=22 state=started

- hosts: web
  become: True

  tasks:

    - name: restart the server (due to an ubuntu/ansible bug)
      command: shutdown -r now
      async: 0
      poll: 0
      ignore_errors: true

- hosts: localhost
  connection: local
  vars:
    ansible_python_interpreter: python
  tasks:

    - name: wait for ssh to be available
      wait_for: host={{ public_v4 }} port=22 state=started

- hosts: web
  become: True

  vars:

  tasks:

